version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
    volumes: 
      - ~/Desktop/learning-to-see-in-the-dark-pytorch/checkpoint:/checkpoint
    environment: 
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
    cap_add:
      - SYS_PTRACE
    ports:
      - "5000:5000"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"