version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
    volumes: 
      - ~/Desktop/learning-to-see-in-the-dark-flask/checkpoint:/checkpoint
      - ~/Desktop/learning-to-see-in-the-dark-flask/src:/app/src
    environment: 
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"